/**
 * Canister client factory.
 * After `dfx generate`, declarations/ will contain the generated IDL + actor.
 * Until then, this file stubs the imports so the frontend compiles.
 */
import { Actor, HttpAgent, type Identity } from '@dfinity/agent'

const CANISTER_ID = (import.meta.env.VITE_CANISTER_ID_BACKEND as string) ?? ''
const DFX_NETWORK = (import.meta.env.VITE_DFX_NETWORK as string) ?? 'local'
const IS_LOCAL    = DFX_NETWORK === 'local'
const IC_HOST     = IS_LOCAL ? 'http://127.0.0.1:4943' : 'https://icp0.io'

async function makeAgent(identity?: Identity): Promise<HttpAgent> {
  const agent = new HttpAgent({ host: IC_HOST, identity })
  if (IS_LOCAL) {
    try { await agent.fetchRootKey() } catch { /* replica may be offline */ }
  }
  return agent
}

// Lazy-load the generated IDL factory so the app still bundles without declarations/
async function loadIdl() {
  try {
    // Generated by `dfx generate backend`
    const mod = await import('../declarations/backend/index.js' as string)
    return mod.idlFactory
  } catch {
    console.warn('[canister] declarations not found — run `dfx generate` first')
    return null
  }
}

/** Anonymous actor for public reads (website). */
export async function queryActor() {
  const idlFactory = await loadIdl()
  if (!idlFactory || !CANISTER_ID) return null
  return Actor.createActor(idlFactory, { agent: await makeAgent(), canisterId: CANISTER_ID })
}

/** Authenticated actor for admin writes. */
export async function updateActor(identity: Identity) {
  const idlFactory = await loadIdl()
  if (!idlFactory || !CANISTER_ID) return null
  return Actor.createActor(idlFactory, { agent: await makeAgent(identity), canisterId: CANISTER_ID })
}

export async function devActor() {
  const idlFactory = await loadIdl();
  if (!idlFactory || !CANISTER_ID) return null;
  return Actor.createActor(idlFactory, {
    agent: await makeAgent(),
    canisterId: CANISTER_ID,
  });
}
